"""empty message

Revision ID: 1074638816c5
Revises: None
Create Date: 2019-10-14 18:58:51.893053

"""

# revision identifiers, used by Alembic.
revision = '1074638816c5'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('payload', sa.Integer(), nullable=True),
    sa.Column('sensor_name', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_measure_datetime'), 'measure', ['datetime'], unique=False)
    op.create_index(op.f('ix_measure_id'), 'measure', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_measure_id'), table_name='measure')
    op.drop_index(op.f('ix_measure_datetime'), table_name='measure')
    op.drop_table('measure')
    # ### end Alembic commands ###
