"""empty message

Revision ID: dd11f59d3fde
Revises: f6cf3dd8c4bc
Create Date: 2019-10-09 19:01:12.541090

"""

# revision identifiers, used by Alembic.
revision = 'dd11f59d3fde'
down_revision = 'f6cf3dd8c4bc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measure', sa.Column('sensor_name', sa.String(length=12), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measure', 'sensor_name')
    # ### end Alembic commands ###
