"""empty message

Revision ID: f6cf3dd8c4bc
Revises: None
Create Date: 2019-10-06 12:45:54.917577

"""

# revision identifiers, used by Alembic.
revision = 'f6cf3dd8c4bc'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('payload', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('measure')
    # ### end Alembic commands ###
